[build]
rustflags = ["-Cforce-frame-pointers=yes"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
runner = ["C:/msys64/mingw64.exe", ".cargo/runner.x86_64.sh"]

[target.aarch64-unknown-none]
runner = ["C:/msys64/mingw64.exe", ".cargo/runner.aarch64.sh"]
