[build]
target = "x86_64-unknown-none"
rustflags = ["-Cforce-frame-pointers=yes"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
runner = ["C:/msys64/mingw64.exe", ".cargo/runner.sh"]
